import StarBorder from "../../star-border/StarBorder";
import "./QnA.css";

function QnA() {
  return (
    <div
      className="qna"
      style={{
        minHeight: "100vh",
        color: "white",
        paddingTop: "10vh",
      }}
    >
      <h1 style={{}}>QnA</h1>
      <div
        style={{
          width: "100vw",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          flexWrap: "wrap",
          margin: 0,
        }}
      >
        <Question
          question="Why is this site so fast?"
          answer="Because I bribe the server with occasional snacks."
          rtl
        />
        <Question
          question="Are you really the one who wrote the code?"
          answer="I did, but I also had a few ‘helpful’ suggestions from Google."
        />
        <Question
          question="Why does the button not work?"
          answer="It’s just playing hard to get. It’ll work when it’s ready."
          rtl
        />
        <Question
          question="Why is there no documentation?"
          answer="Who needs documentation when you can just stare at the code and cry in silence?"
        />
        <Question
          question="How do you handle bugs?"
          answer="I negotiate with them. Sometimes they agree to leave. Sometimes I just ignore them."
          rtl
        />
        <Question
          question="Can I change the theme?"
          answer="Sure, but it won’t change the fact that the code is still a mess."
        />
        <Question
          question="Why is the site layout so simple?"
          answer="Because I was aiming for ‘elegantly minimalist’… or maybe just ‘ran out of time’."
          rtl
        />
        <Question
          question="Is the site mobile-friendly?"
          answer="Yes, unless you're using a toaster with Wi-Fi."
        />
        <Question
          question="How did you optimize the page load time?"
          answer="I stripped it down to the bare essentials. Anything unnecessary? Gone. Except the memes."
          rtl
        />
        <Question
          question="How do you test your code?"
          answer="I test it by hitting refresh and hoping for the best."
        />
        <Question
          question="What’s your secret to clean code?"
          answer="I don’t do clean code. I do code that works... sometimes."
          rtl
        />
        <Question
          question="Why does the site look so modern?"
          answer="It’s a mix of modern design and me pretending to know what I’m doing."
        />
        <Question
          question="Why are there so many comments in the code?"
          answer="They’re not comments, they’re love notes to my future self."
          rtl
        />
        <Question
          question="How secure is this site?"
          answer="It’s secure enough to make hackers second guess their life choices."
        />
        <Question
          question="How do you keep track of bugs?"
          answer="I use a combination of sticky notes, panic, and a healthy dose of denial."
          rtl
        />

        <Question
          question="Where these answers generated by AI?"
          answer="Uhm, well..."
        />
      </div>
    </div>
  );
}

interface QuestionProps {
  question: string;
  answer: string;
  rtl?: boolean;
}

const Question: React.FC<QuestionProps> = ({
  question,
  answer,
  rtl = false,
}) => {
  const questionElement = (
    <StarBorder speed="1s" color="white" as="div">
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          zIndex: "10",
          position: "relative",
          height: "50vh",
          width: "40vw",
        }}
      >
        <span className="question" style={{}}>
          {question}
        </span>
      </div>
    </StarBorder>
  );

  const answerElement = (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        zIndex: "10",
        position: "relative",
        height: "50vh",
        width: "40vw",
      }}
    >
      <br />
      <span className="answer">{answer}</span>
    </div>
  );

  return (
    <div
      style={{
        display: "flex",
        flexDirection: rtl ? "row-reverse" : "row",
        overflow: "hidden",
        width: "100%",
      }}
    >
      <div style={{ padding: "2em", flex: 1 }}>{answerElement}</div>
      <div style={{ padding: "2em", flex: 1 }}>{questionElement}</div>
    </div>
  );
};

export default QnA;
